Assets/lang/es.json, Assets/lang/flagCodes.json
I did not put any accents and I doubt anyone will proof check this :3
=> spanish translation for MCA/AYIM site

Assets/lang/kr.json
general translation by Jakads, categories translation by me
left 'incVote' as blank since we have no idea what it is
=> Add Korean Translation

AYIM/api/routes/records.ts, AYIM/api/routes/statistics.ts, AYIM/pages/_year/mapsets/statistics.vue, Assets/lang/en.json, Assets/lang/example.json
* Added Mapset records
* Updated statistics/records whose values needed to be rounded
* Updated variables to match TL and added new TL titles
=> Additional Statistics, Records, and Translation Fixes

Server/scripts/fetchYearMaps.ts
Can't seem to get my IDE to match your indentation formatting but whatever.
=> Fixed memory overflow issue in fetchYearMaps

.gitignore, Server/discord.ts, Server/passportFunctions.ts
Once again apologies for whatever it is my formatter is doing
=> Stop Discord logging in every time module is imported (e.g. in build)

Server/scripts/fetchYearMaps.ts, package.json
This fixes null creator IDs on beatmapsets.
=> Update DB migration and fetchYearMaps script

AYIM/assets/ayim.scss, AYIM/components/DisplayLayout.vue, AYIM/components/IndexPage.vue, AYIM/pages/_year/comments/index.vue, AYIM/pages/_year/mappers/records.vue, MCA-AYIM/assets/sass/button.scss, MCA-AYIM/assets/sass/layout.scss, MCA-AYIM/components/BaseChoiceCard.vue, MCA-AYIM/components/Collapsible.vue, MCA-AYIM/components/ModeSwitcher.vue, MCA-AYIM/components/SearchBar.vue, MCA/api/routes/nominations.ts, MCA/api/routes/stageSearch.ts, MCA/api/routes/voting.ts, MCA/components/IndexPage.vue, MCA/components/stage/StagePage.vue, MCA/pages/_year/_stage.vue, MCA/pages/_year/index.vue, Main/pages/index.vue
Plus a small fix for non-grand award categories (filter -> .ts files only in files changed tab)
=> Mobile Support

AYIM/pages/_year/comments/_mapper.vue, AYIM/pages/_year/comments/index.vue, MCA-AYIM/assets/sass/button.scss, MCA-AYIM/components/admin/AdminPage.vue
also changed some styles and eslint auto applied on save on some parts mm
=> Visual feedback on comments update

Interfaces/category.ts, MCA-AYIM/components/admin/AdminCategories.vue, MCA-AYIM/components/admin/AdminModalCategory.vue, Models/MCA_AYIM/category.ts, Models/migrations/1620807874196-MCACategoryDescriptionDeletion.ts, Models/migrations/1620809087589-MCACategoryDescriptionDeletion.ts
Useless cuz we just use the i18n jsons for the descriptions anyway using the category name as the key
=> Remove the description field in the category model

AYIM/components/DisplayLayout.vue, AYIM/pages/_year/comments/_mapper.vue, AYIM/pages/_year/comments/index.vue, AYIM/pages/_year/mappers/records.vue, AYIM/pages/_year/mappers/statistics.vue, AYIM/pages/_year/mapsets/records.vue, AYIM/pages/_year/mapsets/statistics.vue, MCA-AYIM/components/ListTransition.vue
=> attempt at group transitions

AYIM/components/DisplayLayout.vue, AYIM/pages/_year/index.vue, MCA-AYIM/components/ModeSwitcher.vue
=> Hide sb icon on ayim

MCA/api/index.ts, MCA/api/middleware.ts, MCA/api/routes/nominating.ts, MCA/api/routes/nominations.ts, MCA/api/routes/voting.ts, Models/MCA_AYIM/vote.ts
- Unable to remove nomination in a different category if nominated in grand as well
- Voting page lets you vote in other categories regardless if you voted in grand award or not
- Voting page shows the popup on requiring you to vote in grand award regardless if you voted in grand award or not
- U cant remove grand user nomination / vote even if u didnt nominate / vote in any other user categories but nominated in beatmap categories that arent required
The above are fixed
Also renamed file and changed eager on for a couple columns in vote model to parallel nomination model
=> Nominating + Voting Bug Fixes

AYIM/api/index.ts, AYIM/pages/_year/admin/index.vue, MCA-AYIM/api/routes/admin/index.ts, MCA-AYIM/api/routes/admin/years.ts, MCA-AYIM/assets/sass/admin.scss, MCA-AYIM/assets/sass/main.scss, MCA/api/index.ts, MCA/api/routes/nominating.ts, MCA/api/routes/voting.ts, MCA/pages/_year/admin/index.vue, Server/cache.ts, Server/index.ts
=> Cache changes + Deletion methods

Assets/lang/es.json
my json might be haunted at vinxis
=> update es tl

Models/user.ts, Server/discord.ts, Server/middleware.ts
reduce code redundancy from https://github.com/Corsace/Corsace/compare/3861ea98edc9...bd77626d7b3c
=> getMember function to fetch member

MCA-AYIM/assets/sass/staff.scss, MCA-AYIM/components/BaseChoiceCard.vue, MCA-AYIM/components/ScrollBar.vue, MCA/components/results/ResultsTableHeadings.vue, MCA/pages/_year/results.vue, package-lock.json, package.json
- removes [this](https://i.imgur.com/0iC18u3.png) extra space by shrinking vote #
- fixes [this](https://cdn.discordapp.com/attachments/789808737594245141/868276531368169472/unknown.png) behaviour where inactive categories still stack on top (from position: sticky;)
- fixes a surplus of nominators/voters from overflowing staff pg scrolltrack
=> Staff + vote page ui fixes

Assets/lang/en.json, Interfaces/result.ts, Interfaces/vote.ts, MCA-AYIM/components/DropdownSelector.vue, MCA/components/results/ResultsBeatmapsetCard.vue, MCA/components/results/ResultsTableHeadings.vue, MCA/components/results/ResultsUserCard.vue, MCA/components/staff/StaffVoteAccordion.vue, MCA/pages/_year/results.vue
make sure i didnt destroy corsace as we know it
did some minor css changes on results pg cuz cols werent aligning cuz of some padding thing i had to make things truncate cleaner
removed that for now but ideally it (or smth similar) would get put back in
=> Replace total choices field of results with 2nd/3rd choices

Assets/lang/en.json, Interfaces/result.ts, MCA-AYIM/components/DropdownSelector.vue, MCA/components/results/ResultsFilters.vue, MCA/components/results/ResultsTableHeadings.vue, MCA/pages/_year/results.vue, package-lock.json, package.json
tried using $te to check for a translation key instead of adding a new field to ResultsColumn but it didn't work for some reason
that's a more maintainable way of adding tooltips so if you can get that to work it'd be better than current
=> Adjust results page for new vote data + add explanatory tooltips

Assets/lang/en.json, Interfaces/result.ts, MCA-AYIM/components/DropdownSelector.vue, MCA/components/results/ResultsFilters.vue, MCA/components/results/ResultsTableHeadings.vue, MCA/pages/_year/results.vue, package-lock.json, package.json
=> Revert "Adjust results page for new vote data + add explanatory tooltips"

DiscordBot/commands/mappool/assign.ts, DiscordBot/commands/mappool/assignments.ts, DiscordBot/commands/mappool/deadline.ts, DiscordBot/commands/mappool/download.ts, DiscordBot/commands/mappool/info.ts, DiscordBot/commands/mappool/remove.ts, DiscordBot/commands/mappool/submit.ts, DiscordBot/commands/mappool/swap.ts, DiscordBot/functions/mappoolFunctions.ts, Server/BeatmapParser.ts, Server/sheets.ts, package-lock.json, package.json
Also an extra check for if the round exists in the tournament in the first place
=> Fetching Beatmap Info for Mappool Submission

DiscordBot/functions/mappoolFunctions.ts
=> FIX MAPPOOL ACRONYMS + STRONGER USER CHECKS

Interfaces/beatmap.ts, Interfaces/category.ts, Interfaces/nomination.ts, Interfaces/result.ts, Interfaces/vote.ts, MCA-AYIM/components/BaseChoiceCard.vue, MCA-AYIM/components/ChoiceBeatmapsetCard.vue, MCA-AYIM/components/admin/AdminModalCategory.vue, MCA-AYIM/store/stage.ts, MCA/api/routes/nominating.ts, MCA/api/routes/results.ts, MCA/api/routes/staff/nominations.ts, MCA/api/routes/staff/votes.ts, MCA/api/routes/stageSearch.ts, MCA/api/routes/voting.ts, MCA/components/results/ResultsBeatmapsetCard.vue, MCA/components/staff/StaffNomAccordion.vue, MCA/components/staff/StaffVoteAccordion.vue, MCA/components/stage/StagePageList.vue, MCA/pages/_year/results.vue, Models/MCA_AYIM/category.ts, Models/MCA_AYIM/nomination.ts, Models/MCA_AYIM/vote.ts, Models/beatmap.ts, Models/migrations/1643610856614-MCANominateVoteBeatmaps.ts
Moving from sets for 2021 onward most likely
=> Difficulty based nomination + voting

DiscordBot/commands/mappool/download.ts, DiscordBot/commands/mappool/swap.ts, DiscordBot/functions/mappoolFunctions.ts, Interfaces/mods.ts, Main/pages/index.vue
- Show full pool even over 2000 chars
- Extension of the fix we did in https://github.com/Corsace/Corsace/pull/120 since f queried to a user that is mapping for the tournament instead of considering the letter as finals
Also fixed avatar height on main site
=> Bug fixes on discord bot pooling

Assets/lang/cn.json
Pretty simple one
Extra: i would like to help contribute to the translation in Corsace open (cuz there's some weird translation), but i didnt find the localization strings here, do i have any way to help translate Corsace open?
=> Update and format Simplified Chinese localisation

Assets/lang/cn.json, Assets/lang/en.json, Assets/lang/id.json, Assets/lang/jp.json, Assets/lang/kr.json, MCA/api/routes/nominating.ts, MCA/api/routes/stageSearch.ts, Server/api/routes/login/osu.ts, Server/api/routes/user.ts, Server/scripts/fetchYearMaps.ts
- Allow username additions for when no username (NOTE: Need to keep in mind and update the fetchyearmaps script becuase it generated 2 users with no usernames)
- Allow username removals for extra names that contain dox info
- Fix nomination structure for beatmaps
- Add BPM note for High BPM category
- Fix played filter
=> MCA 2021 Fixes

MCA/api/routes/nominating.ts, MCA/api/routes/stageSearch.ts, Models/MCA_AYIM/guestRequest.ts, Server/api/routes/login/osu.ts, Server/scripts/fetchYearMaps.ts
=> Guest Diff Helper Func + Remove Redundant played filter url param

Models/user.ts
=> Guest Diff Check Update for the SQL query too 

Assets/lang/jp.json
added "diversity category" and also fixed the "Tap Trio - Corsace Bundle" part
=> jp translation for "diversity" category

Assets/lang/fr.json
Added TechnicalCatch, antimeta and diversity categories to fr.json
=> French Translation

Assets/lang/id.json
=> Update Indonesian localization (`/assets/lang/id.json`) for the new award categories

AYIM/api/bnNatHistory.ts, AYIM/api/routes/statistics.ts
=> Add 2022 BN/NAT stats

DiscordBot/commands/index.ts, DiscordBot/commands/tournaments/create.ts, DiscordBot/commands/tournaments/mappool/assign.ts, DiscordBot/commands/tournaments/mappool/assignments.ts, DiscordBot/commands/tournaments/mappool/deadline.ts, DiscordBot/commands/tournaments/mappool/download.ts, DiscordBot/commands/tournaments/mappool/info.ts, DiscordBot/commands/tournaments/mappool/jobBoard/info.ts, DiscordBot/commands/tournaments/mappool/jobBoard/job.ts, DiscordBot/commands/tournaments/mappool/jobBoard/publish.ts, DiscordBot/commands/tournaments/mappool/remove.ts, DiscordBot/commands/tournaments/mappool/submit.ts, DiscordBot/commands/tournaments/mappool/swap.ts, DiscordBot/functions/tournamentFunctions.ts, DiscordBot/handlers/interactionCreate.ts, DiscordBot/handlers/messageCreate.ts, Models/migrations/1683581603217-jobBoard.ts, Models/tournaments/mappools/jobPost.ts, Models/tournaments/mappools/mappool.ts, Models/tournaments/mappools/mappoolMap.ts, Models/tournaments/mappools/mappoolSlot.ts, Models/tournaments/tournamentChannel.ts, Models/user.ts
As per Halfslashed's request
Also includes fixes and QOL changes from further testing
=> Mappool Job Board Discord Functionality

DiscordBot/commands/tournaments/create.ts, DiscordBot/commands/tournaments/mappool/jobBoard/job.ts, Models/migrations/1685372691373-increaseDescriptionSize.ts, Models/tournaments/mappools/jobPost.ts, Models/tournaments/tournament.ts
=> Increase Tournament + Job Post Description Sizes

DiscordBot/commandsInexplicit/osu/osuTimestamp.ts, DiscordBot/handlers/messageCreate.ts, Server/api/routes/osuuri.ts, Server/index.ts
=> Re-implement osu uri conversion for osu! editor timestamps

Assets/lang/nl.json
=> nl translatotujeani

Assets/components/open/OpenInput.vue, Assets/components/open/OpenSelect.vue, Assets/lang/en.json, Interfaces/osuAPIV2.ts, Interfaces/team.ts, Models/MCA_AYIM/modeDivision.ts, Models/migrations/1689519479259-statsAndTimezone.ts, Models/tournaments/team.ts, Models/user.ts, Models/userStatistics.ts, Open/pages/team/_id.vue, Open/pages/team/create.vue, Server/api/routes/login/osu.ts, Server/api/routes/team/index.ts, Server/api/routes/tournament/index.ts, Server/cron/cronFunctions/tournamentRegistrationEnd.ts, Server/functions/get/getTeamInvites.ts, Server/functions/get/getTeams.ts, Server/osu/osuAPIV2.ts, Server/utils/dateParse.ts
Should tremendously reduce osu! API calls and make things faster
Also added a timezone field for teams
=> User Statistics and Team Timezone

BanchoBot/functions/tournaments/matchup/runMatchup.ts, DiscordBot/commands/tournaments/team/invite.ts, DiscordBot/commands/tournaments/team/schedule.ts, Server/api/routes/qualifier.ts
=> More fixes to discord bot, qualifiers, and save mp lobbies

Server/api/routes/guestRequests.ts, Server/api/routes/login/osu.ts, Server/api/routes/users.ts, Server/osu/index.ts, Server/passportFunctions.ts, Server/scripts/fetchYearMaps.ts, config/Config.d.ts, config/deployment/production.json, corsace-chart/templates/_helpers.tpl, corsace-chart/templates/secret.yaml, corsace-chart/values.yaml
Ideally we should remove the isolated API calls..
=> ✨ Use the osu! API rate-limiting proxy everywhere we should

DiscordBot/commands/tournaments/channel.ts, DiscordBot/commands/tournaments/create.ts, Interfaces/modes.ts, Models/tournaments/tournamentChannel.ts, Models/user.ts
=> Turn Enum Dict Objects Into Functions

BanchoBot/functions/tournaments/matchup/runMatchup.ts, DiscordBot/commands/tournaments/matchup/scores.ts, Models/tournaments/matchupMap.ts, Models/tournaments/matchupScore.ts, Server/api/routes/qualifier.ts, Server/osu/osuAPIV2.ts
- score addition endpoint
- score removal endpoint
- map removal endpoint
- fix to scores discord command
we're gonna need a MatchupNote model later to note of any manual changes to things
=> Endpoints and fixes for scores manipulation and fetching

Models/migrations/1690328808731-databaseTeamRegistrationTriggers.ts, Server/api/routes/team/index.ts
made 1 for team creation, and 1 for team registration
=> MariaDB triggers to handle race conditions in team creation/registration

BanchoBot/functions/tournaments/matchup/runMatchup.ts
- text fixes
- state matchupID index check
- some more text clarity i think.....
=> Further general improvements for matchupRun 

Assets/components/open/OpenTitle.vue, Assets/components/open/ScoresView.vue, Interfaces/qualifier.ts, Open/pages/qualifiers.vue, Server/api/routes/qualifier.ts, Server/api/routes/tournament/index.ts
Why did this fucking take me 3 days
=> Score table improvements

.gitignore, DiscordBot/commands/tournaments/matchup/reschedule.ts, Open/pages/schedule.vue, README.md, Server/api/routes/centrifugo.ts, Server/index.ts, centrifugo-config.json, config/Config.d.ts, config/default.json, config/deployment/production.json, docker-compose.yml, package-lock.json, package.json
connection and subscription tested by adding in `Open/pages/index.vue`:
```typescript
async mounted () {
await this.$store.dispatch("setInitialData", "open");
const centrifuge = new Centrifuge("ws://localhost:8001/connection/websocket");
centrifuge.on("connecting", () => {
console.log("connecting");
});
centrifuge.on("error", (err) => {
console.error("error", err);
});
centrifuge.on("connected", () => {
console.log("connected");
});
const sub = centrifuge.newSubscription("testingChannel");
sub.on("subscribed", () => {
console.log("subscribed");
});
sub.subscribe();
centrifuge.connect();
}
```
i have not implemented/tested publishing messages from the backend because i didn't know where it'd be best to. but i have added the required config options and it's pretty easy: …
=> ✨ Bootstrap centrifugo

Assets/components/open/ScoresView.vue, Assets/lang/en.json, Interfaces/matchup.ts, Open/pages/mappool.vue, Open/pages/qualifier/_id.vue, Open/pages/qualifiers.vue
=> Better Functioning Score table improvements

DiscordBot/commands/tournaments/matchup/reschedule.ts, Open/pages/mappool.vue, Open/pages/qualifiers.vue, Open/pages/schedule.vue, Open/store/open.ts, Server/api/routes/login/osu.ts, Server/api/routes/stage/index.ts, Server/api/routes/tournament/index.ts
=> Misc. Fixes to osu!apiV1/DB querying

README.md, Server/api/routes/github.ts, Server/index.ts, config/Config.d.ts, config/default.json, config/deployment/production.json, corsace-chart/templates/_helpers.tpl, corsace-chart/templates/secret.yaml, corsace-chart/values.yaml
So we can uhhhh kill crowdin spam
=> Custom GitHub Webhook

BanchoBot/functions/tournaments/matchup/runMatchup.ts
re: https://discord.com/channels/461569547145838596/1139962410468388864/1150161577589354516
- also includes the beginning of changing the name managers to captains
=> Text changes for bancho matchup runner

Assets/lang/en.json
hopefully i didnt miss anything
=> add MCA 2023 new categories

DiscordBot/commands/tournaments/create.ts, DiscordBot/commands/tournaments/role.ts, DiscordBot/functions/tournamentFunctions/getTournament.ts
2 changes:
Add fixes to null user for role/channel additions
Add channel check for tournament list first before server check for tournament list
=> Fix NULL user for trole/channel creations and channel check for tournament list

config/Config.d.ts, config/default.json, config/deployment/production.json, corsace-chart/templates/secret.yaml
We aren't using it anymore anwyay
=> Remove google credentials from config

DiscordBot/commands/tournaments/info.ts, DiscordBot/functions/parameterFunctions.ts
=> Add more functionality to the tinfo command

Assets/mixins/centrifuge.ts, BanchoBot/functions/tournaments/matchup/centrifugo.ts, BanchoBot/functions/tournaments/matchup/runMatchup.ts, Open/layouts/default.vue, Open/pages/referee/_id.vue, Open/pages/teams.vue, Open/store/open.ts, Server/api/routes/bancho/referee.ts, Server/api/routes/centrifugo.ts, Server/api/routes/team/index.ts, Server/api/routes/team/invite.ts, Server/functions/centrifugo.ts, Typing/centrifuge-shim.d.ts, centrifugo-config.json
Now people can see teams registering in real-time on site, and also get their invitations from teams real-time on site
=> Use Centrifugo for real-time updates for registered teams and users getting invites from teams

DiscordBot/commands/index.ts, DiscordBot/commands/osu/contentUsage.ts, DiscordBot/functions/respond.ts, Interfaces/osuAPIV2.ts, Server/osu/osuAPIV2.ts, Server/osu/osuWikiCache.ts
=> Create osu! artist content usage command

Models/migrations/1721168567643-updateValidateQualifierMatchup.ts
=> Fix DB Trigger looking at every qualifier stage

BanchoBot/functions/tournaments/matchup/runMatchup.ts
=> Abstract panic functionality and add check for empty lobby

DiscordBot/commands/index.ts, DiscordBot/commands/tournaments/mappool/download.ts, DiscordBot/commands/tournaments/mappool/replay.ts, DiscordBot/commands/tournaments/mappool/replay/download.ts, DiscordBot/commands/tournaments/mappool/replay/index.ts, DiscordBot/functions/beatmapParse.ts, DiscordBot/functions/replayParse.ts, DiscordBot/functions/tournamentFunctions/getMappoolSlot.ts, Models/beatmap.ts, Models/migrations/1722301637126-replayAndMD5Hashes.ts, Models/tournaments/mappools/customBeatmap.ts, Models/tournaments/mappools/mappoolReplay.ts, Server/scripts/fetchYearMaps.ts
=> Add replay parsing and downloading functionality

Assets/components/open/ScheduleMatchBox.vue, Interfaces/matchup.ts, Models/migrations/1722799758998-matchIDLabels.ts, Models/tournaments/matchup.ts, Models/tournaments/team.ts, Server/api/routes/matchup.ts, Server/api/routes/stage/index.ts, Server/functions/tournaments/matchups/dbMatchupToInterface.ts
So now matches can be `A1` or w/e
=> Add custom match ID labels to matchups

Server/api/routes/stage/index.ts, Server/middleware/tournament.ts
Measuring 350ms on my laptop on power-saving despite more round-trips and shit wifi and remote db.
vs. 5~9s in production.
Yeah
=> ⚡️ Optimize stage matchups listing

Server/api/routes/tournament/index.ts
50~70% savings, byte-identical output on production corsace open 2024
=> ⚡️ Optimize tournament team listings

Server/api/routes/tournament/index.ts
30~50% savings, byte-identical output on production corsace open 2024
=> ⚡️ Optimize tournament qualifier results

Assets/components/open/ScheduleMatchBox.vue, Assets/components/open/ScheduleMatchBoxTeam.vue, Assets/lang/en.json, BanchoBot/functions/tournaments/matchup/runMatchup.ts, DiscordBot/commands/tournaments/matchup/reschedule.ts, Interfaces/matchup.ts, Models/migrations/1723420602417-matchupConnectionChanges.ts, Models/migrations/1723429054291-matchupConnectionChanges.ts, Models/tournaments/matchup.ts, Open/pages/schedule.vue, Server/api/routes/matchup.ts, Server/api/routes/stage/index.ts, Server/functions/tournaments/matchups/assignTeamsToNextMatchup.ts
kill previousMatchups in matchup
add previousLoserMatchups and previousWinnerMatchups in matchup (and a trigger)
=> Changing how PrevMatchup Connections are Made

Server/api/routes/stage/index.ts
I think it's the last public endpoint with bad response time on Open. I figured a proper permanent data structure for this would not come for a while, so I came up with a low-effort work-around for now.
=> ⚡️ Cache mappool beatmaps with modded stats

BanchoBot/functions/tournaments/matchup/runMatchup.ts, Server/api/routes/bancho/referee.ts, Server/api/routes/matchup.ts, Server/functions/tournaments/matchups/assignTeamsToNextMatchup.ts
changes to forfeit are actually relevant
=> Functionality to auto assign teams after matchup finishes

Server/api/routes/admin/index.ts, Server/api/routes/admin/years.ts
=> remove cache.del and cache.reset calls

BanchoBot/functions/tournaments/matchup/runMatchup.ts, DiscordBot/commands/tournaments/info.ts, Models/tournaments/round.ts, Server/api/routes/bancho/index.ts, Server/api/routes/bancho/referee.ts, Server/api/routes/matchup.ts, Server/functions/tournaments/matchups/dbMatchupToInterface.ts
Untested cuz idk how to test easily but also reliably....
=> SQL Query Optimizations for instances where runMatchup is used

Server/api/routes/qualifier.ts
Tested against `/api/matchup/463`: ~1100ms -> ~120ms (and much less resources usage as expected) with byte-identical output
=> ⚡️ Optimize single qualifier result queries

Server/api/routes/tournament/index.ts, Server/discord.ts
Had to ditch some middleware for testing, didn't realize I'd be breaking `hasRoles` by removing `validateTournament`.
=> Hotfix #357

BanchoBot/functions/tournaments/matchup/runMatchup.ts, Server/api/routes/bancho/referee.ts, Server/api/routes/matchup.ts, Server/api/routes/team/index.ts, Server/api/routes/team/invite.ts, Server/functions/centrifugo.ts
What back-end components send to Centrifugo is purely for client-side reactivity, is not critical and should never cause a failure in back-end components.
=> 🥅 Log and never fail on Centrifugo errors

Server/api/routes/bancho/index.ts
Fixes multiple lobbies getting created for the same matchup due to players triggering concurrent calls by rescheduling literally last 3.3s
=> 🚑️ Queue runQualifiers executions

BanchoBot/functions/tournaments/matchup/getUserInMatchup.ts, Models/migrations/1755263236438-userOsuIrcUsername.ts, Models/user.ts
Includes a migration
Fixes #406
=> Fix messages sent via IRC by users with spaces in their username getting attributed to BanchoBot

DiscordBot/commands/tournaments/matchup/reschedule.ts
=> 🐛 Fix organizers not being able to force-reschedule a match if they're the assigned referee
